sudo: false # route your build to the container-based infrastructure for a faster build
language: ruby
rvm:
- 2.5.1

branches:
  only:
  - jekyll

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer # https://github.com/gjtorikian/html-proofer/issues/381

before_install:
- openssl aes-256-cbc -K $encrypted_4141ce77cc08_key -iv $encrypted_4141ce77cc08_iv
  -in redhat-cop-deploy-key.enc -out ~\/.ssh/redhat-cop-deploy-key -d
before_script:
 - chmod +x ./script/*
 - gem --version
 - gem install bundler
script:
- "./ci/build.sh"
- "./cd/deploy.sh"

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
